FROM node:16
  
ENV PORT 3000

ENV NODE_HEAPDUMP_OPTIONS nosignal

# Install OS updates
RUN apt-get update && apt-get install bc \
 && echo 'Finished installing dependencies'

WORKDIR "/app"

COPY run-dev.sh /bin
COPY run-debug.sh /bin

RUN chmod 777 /bin/run-dev.sh /bin/run-debug.sh

# Install nodemon for use with "dev" mode
RUN npm install -g nodemon

# Bundle app source and install dependencies
COPY . /app
RUN npm install

EXPOSE 3000

USER node

CMD ["/bin/bash"]
